[2024-05-09T12:00:02.639+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T12:00:02.668+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T10:00:00+00:00 [queued]>
[2024-05-09T12:00:02.675+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T10:00:00+00:00 [queued]>
[2024-05-09T12:00:02.676+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T12:00:02.687+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 10:00:00+00:00
[2024-05-09T12:00:02.692+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2155) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T12:00:02.693+0000] {standard_task_runner.py:63} INFO - Started process 2156 to run task
[2024-05-09T12:00:02.692+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T10:00:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmpyv79tomr']
[2024-05-09T12:00:02.694+0000] {standard_task_runner.py:91} INFO - Job 121: Subtask except_friday_run_database_task
[2024-05-09T12:00:02.711+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T12:00:02.745+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T10:00:00+00:00 [running]> on host 5d069ed3d57a
[2024-05-09T12:00:02.824+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T10:00:00+00:00'
[2024-05-09T12:00:02.825+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T12:00:02.842+0000] {logging_mixin.py:188} INFO - Successfully deleted table 'incidence_table'
[2024-05-09T12:00:02.847+0000] {logging_mixin.py:188} INFO - Successfully created table 'incidence_table'
[2024-05-09T12:00:02.855+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-09T12:00:02.856+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T12:00:02.865+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T10:00:00+00:00, execution_date=20240509T100000, start_date=20240509T120002, end_date=20240509T120002
[2024-05-09T12:00:02.907+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T12:00:02.921+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T12:00:02.923+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-09T17:14:12.362+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T17:14:12.411+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T10:00:00+00:00 [queued]>
[2024-05-09T17:14:12.418+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T10:00:00+00:00 [queued]>
[2024-05-09T17:14:12.419+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T17:14:12.439+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 10:00:00+00:00
[2024-05-09T17:14:12.446+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=274) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T17:14:12.451+0000] {standard_task_runner.py:63} INFO - Started process 279 to run task
[2024-05-09T17:14:12.451+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T10:00:00+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmpq9u4smje']
[2024-05-09T17:14:12.453+0000] {standard_task_runner.py:91} INFO - Job 194: Subtask except_friday_run_database_task
[2024-05-09T17:14:12.472+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T17:14:12.530+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T10:00:00+00:00 [running]> on host 2ac721f319c6
[2024-05-09T17:14:12.678+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T10:00:00+00:00'
[2024-05-09T17:14:12.680+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T17:14:12.733+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T17:14:12.735+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/single_dag.py", line 101, in insert_data_to_table
    cur.execute("""
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(incidence_table_id_seq, 2200) already exists.

[2024-05-09T17:14:12.767+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T10:00:00+00:00, execution_date=20240509T100000, start_date=20240509T171412, end_date=20240509T171412
[2024-05-09T17:14:12.785+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 194 for task except_friday_run_database_task (duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(incidence_table_id_seq, 2200) already exists.
; 279)
[2024-05-09T17:14:12.793+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T17:14:12.808+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T17:14:12.811+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-09T18:32:07.930+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T18:32:08.049+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T10:00:00+00:00 [queued]>
[2024-05-09T18:32:08.065+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T10:00:00+00:00 [queued]>
[2024-05-09T18:32:08.065+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T18:32:08.089+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 10:00:00+00:00
[2024-05-09T18:32:08.097+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=415) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T18:32:08.099+0000] {standard_task_runner.py:63} INFO - Started process 422 to run task
[2024-05-09T18:32:08.111+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T10:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmp_wz5t0dj']
[2024-05-09T18:32:08.113+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask except_friday_run_database_task
[2024-05-09T18:32:08.216+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T18:32:08.442+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T10:00:00+00:00 [running]> on host def55370f167
[2024-05-09T18:32:08.844+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T10:00:00+00:00'
[2024-05-09T18:32:08.848+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T18:32:09.039+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T18:32:09.040+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/single_dag.py", line 101, in insert_data_to_table
    cur.execute("""
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(incidence_table_id_seq, 2200) already exists.

[2024-05-09T18:32:09.101+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T10:00:00+00:00, execution_date=20240509T100000, start_date=20240509T183208, end_date=20240509T183209
[2024-05-09T18:32:09.151+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 49 for task except_friday_run_database_task (duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(incidence_table_id_seq, 2200) already exists.
; 422)
[2024-05-09T18:32:09.162+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T18:32:09.253+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T18:32:09.260+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
