[2024-05-09T08:24:02.699+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T08:24:02.728+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag.run_crawler_task manual__2024-05-09T08:24:02.150660+00:00 [queued]>
[2024-05-09T08:24:02.735+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag.run_crawler_task manual__2024-05-09T08:24:02.150660+00:00 [queued]>
[2024-05-09T08:24:02.736+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-09T08:24:02.748+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_crawler_task> on 2024-05-09 08:24:02.150660+00:00
[2024-05-09T08:24:02.753+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=285) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T08:24:02.753+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag', 'run_crawler_task', 'manual__2024-05-09T08:24:02.150660+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmp7ewnds82']
[2024-05-09T08:24:02.754+0000] {standard_task_runner.py:63} INFO - Started process 286 to run task
[2024-05-09T08:24:02.755+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask run_crawler_task
[2024-05-09T08:24:02.770+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T08:24:02.802+0000] {task_command.py:426} INFO - Running <TaskInstance: dag.run_crawler_task manual__2024-05-09T08:24:02.150660+00:00 [running]> on host 5d069ed3d57a
[2024-05-09T08:24:02.880+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag' AIRFLOW_CTX_TASK_ID='run_crawler_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T08:24:02.150660+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T08:24:02.150660+00:00'
[2024-05-09T08:24:02.881+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T08:24:02.892+0000] {single_dag.py:52} INFO - This is an informational message
[2024-05-09T08:24:02.893+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T08:24:02.893+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/single_dag.py", line 58, in run_crawler
    for website in websites.items():
                   ^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'items'
[2024-05-09T08:24:02.908+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag, task_id=run_crawler_task, run_id=manual__2024-05-09T08:24:02.150660+00:00, execution_date=20240509T082402, start_date=20240509T082402, end_date=20240509T082402
[2024-05-09T08:24:02.918+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task run_crawler_task ('tuple' object has no attribute 'items'; 286)
[2024-05-09T08:24:02.928+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T08:24:02.947+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T08:24:02.950+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
