[2024-05-09T17:14:12.411+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T17:14:12.447+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T12:00:00+00:00 [queued]>
[2024-05-09T17:14:12.458+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T12:00:00+00:00 [queued]>
[2024-05-09T17:14:12.459+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T17:14:12.475+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 12:00:00+00:00
[2024-05-09T17:14:12.482+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=275) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T17:14:12.482+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T12:00:00+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmpoo952jej']
[2024-05-09T17:14:12.483+0000] {standard_task_runner.py:63} INFO - Started process 284 to run task
[2024-05-09T17:14:12.484+0000] {standard_task_runner.py:91} INFO - Job 200: Subtask except_friday_run_database_task
[2024-05-09T17:14:12.518+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T17:14:12.578+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T12:00:00+00:00 [running]> on host 2ac721f319c6
[2024-05-09T17:14:12.691+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T12:00:00+00:00'
[2024-05-09T17:14:12.693+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T17:14:12.729+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T17:14:12.730+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/single_dag.py", line 101, in insert_data_to_table
    cur.execute("""
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(incidence_table_id_seq, 2200) already exists.

[2024-05-09T17:14:12.764+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T12:00:00+00:00, execution_date=20240509T120000, start_date=20240509T171412, end_date=20240509T171412
[2024-05-09T17:14:12.778+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 200 for task except_friday_run_database_task (duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(incidence_table_id_seq, 2200) already exists.
; 284)
[2024-05-09T17:14:12.821+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T17:14:12.837+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T17:14:12.839+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-09T18:32:07.982+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T18:32:08.105+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T12:00:00+00:00 [queued]>
[2024-05-09T18:32:08.127+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T12:00:00+00:00 [queued]>
[2024-05-09T18:32:08.128+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T18:32:08.157+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 12:00:00+00:00
[2024-05-09T18:32:08.163+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=416) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T18:32:08.165+0000] {standard_task_runner.py:63} INFO - Started process 424 to run task
[2024-05-09T18:32:08.163+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T12:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmp48rmimw8']
[2024-05-09T18:32:08.168+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask except_friday_run_database_task
[2024-05-09T18:32:08.244+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T18:32:08.498+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T12:00:00+00:00 [running]> on host def55370f167
[2024-05-09T18:32:08.943+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T12:00:00+00:00'
[2024-05-09T18:32:08.944+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T18:32:09.040+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T18:32:09.048+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/single_dag.py", line 101, in insert_data_to_table
    cur.execute("""
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(incidence_table_id_seq, 2200) already exists.

[2024-05-09T18:32:09.128+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T12:00:00+00:00, execution_date=20240509T120000, start_date=20240509T183208, end_date=20240509T183209
[2024-05-09T18:32:09.171+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 55 for task except_friday_run_database_task (duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(incidence_table_id_seq, 2200) already exists.
; 424)
[2024-05-09T18:32:09.199+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T18:32:09.281+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T18:32:09.289+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
