[2024-05-09T08:28:43.278+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T08:28:43.314+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag.run_crawler_task scheduled__2024-05-09T04:00:00+00:00 [queued]>
[2024-05-09T08:28:43.323+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag.run_crawler_task scheduled__2024-05-09T04:00:00+00:00 [queued]>
[2024-05-09T08:28:43.325+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-09T08:28:43.341+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_crawler_task> on 2024-05-09 04:00:00+00:00
[2024-05-09T08:28:43.348+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=267) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T08:28:43.348+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag', 'run_crawler_task', 'scheduled__2024-05-09T04:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmpfthcs3ew']
[2024-05-09T08:28:43.351+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask run_crawler_task
[2024-05-09T08:28:43.350+0000] {standard_task_runner.py:63} INFO - Started process 273 to run task
[2024-05-09T08:28:43.367+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T08:28:43.405+0000] {task_command.py:426} INFO - Running <TaskInstance: dag.run_crawler_task scheduled__2024-05-09T04:00:00+00:00 [running]> on host 5d069ed3d57a
[2024-05-09T08:28:43.496+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag' AIRFLOW_CTX_TASK_ID='run_crawler_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T04:00:00+00:00'
[2024-05-09T08:28:43.497+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T08:28:43.507+0000] {single_dag.py:52} INFO - This is an informational message
[2024-05-09T08:28:43.508+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T08:28:43.509+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/single_dag.py", line 58, in run_crawler
    for website in websites.items():
                   ^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'items'
[2024-05-09T08:28:43.522+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag, task_id=run_crawler_task, run_id=scheduled__2024-05-09T04:00:00+00:00, execution_date=20240509T040000, start_date=20240509T082843, end_date=20240509T082843
[2024-05-09T08:28:43.532+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task run_crawler_task ('tuple' object has no attribute 'items'; 273)
[2024-05-09T08:28:43.568+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T08:28:43.587+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T08:28:43.594+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
